export const STAKEMATE_ABI = [
  'function challengeCount() view returns (uint256)',
  'function soloGoalCount() view returns (uint256)',
  'function claimable(address) view returns (uint256)',
  'function challenges(uint256) view returns (address creator,address partner,address forfeitureRecipient,uint256 stakeAmount,uint256 createdAt,uint256 startTime,uint256 endTime,uint16 durationDays,uint16 requiredCheckIns,uint16 creatorCheckIns,uint16 partnerCheckIns,uint8 status,uint8 outcome,string title,uint8 verificationMode,uint8 payoutMode,uint32 reviewPeriod,uint256 reviewDeadline)',
  'function evidenceByParticipant(uint256,address) view returns (bytes32 digest,string uri,uint256 submittedAt,uint8 decision)',
  'function soloGoals(uint256) view returns (address owner,address verifier,address failureRecipient,uint256 amount,uint256 createdAt,uint256 acceptedAt,uint256 goalDeadline,uint256 reviewDeadline,uint256 resolvedAt,uint32 goalDuration,uint32 reviewPeriod,bytes32 resolutionDigest,uint8 status,string title)',
  'function soloGoalEvidence(uint256) view returns (bytes32 digest,string uri,uint256 submittedAt,uint8 decision)',
  'function hasCheckedIn(uint256,address,uint256) view returns (bool)',
  'function currentDayIndex(uint256) view returns (uint256)',
  'function createChallenge(address,address,uint16,uint16,string) payable returns (uint256)',
  'function createEvidenceChallenge(address,address,uint16,uint32,string) payable returns (uint256)',
  'function joinChallenge(uint256) payable',
  'function checkIn(uint256)',
  'function submitEvidence(uint256,bytes32,string)',
  'function reviewEvidence(uint256,address,bool)',
  'function finalizeChallenge(uint256)',
  'function cancelUnjoinedChallenge(uint256)',
  'function createSoloGoal(address,address,uint32,uint32,string) payable returns (uint256)',
  'function acceptSoloGoal(uint256)',
  'function cancelPendingSoloGoal(uint256)',
  'function submitSoloGoalEvidence(uint256,bytes32,string)',
  'function approveSoloGoal(uint256)',
  'function rejectSoloGoal(uint256,bytes32)',
  'function finalizeExpiredSoloGoal(uint256)',
  'function withdrawPayout()',
  'error InvalidAddress()',
  'error InvalidStake()',
  'error InvalidDuration()',
  'error InvalidRequiredCheckIns()',
  'error InvalidReviewPeriod()',
  'error InvalidTitle()',
  'error InvalidEvidence()',
  'error InvalidStatus()',
  'error NotCreator()',
  'error NotInvitedPartner()',
  'error NotParticipant()',
  'error NotReviewer()',
  'error NotGoalOwner()',
  'error NotGoalVerifier()',
  'error AlreadyCheckedIn()',
  'error AlreadyReviewed()',
  'error ChallengeEnded()',
  'error ChallengeNotEnded()',
  'error ReviewStillOpen()',
  'error ReviewWindowClosed()',
  'error ApprovalTooEarly()',
  'error GoalSubmissionClosed()',
  'error GoalNotExpired()',
  'error WrongVerificationMode()',
  'error NothingToWithdraw()',
  'event ChallengeCreated(uint256 indexed challengeId,address indexed creator,address indexed partner,uint256 stakeAmount,uint16 durationDays,uint16 requiredCheckIns,address forfeitureRecipient,uint8 verificationMode,uint8 payoutMode,uint32 reviewPeriod,string title)',
  'event ChallengeJoined(uint256 indexed challengeId,uint256 startTime,uint256 endTime,uint256 reviewDeadline)',
  'event CheckedIn(uint256 indexed challengeId,address indexed participant,uint256 indexed dayIndex)',
  'event EvidenceSubmitted(uint256 indexed challengeId,address indexed participant,bytes32 digest,string uri)',
  'event EvidenceReviewed(uint256 indexed challengeId,address indexed reviewer,address indexed participant,uint8 decision)',
  'event EvidenceAutoApproved(uint256 indexed challengeId,address indexed participant)',
  'event ChallengeFinalized(uint256 indexed challengeId,uint8 outcome,bool creatorSucceeded,bool partnerSucceeded)',
  'event ChallengeCancelled(uint256 indexed challengeId)',
  'event SoloGoalCreated(uint256 indexed soloGoalId,address indexed owner,address indexed verifier,address failureRecipient,uint256 amount,uint32 goalDuration,uint32 reviewPeriod,string title)',
  'event SoloGoalAccepted(uint256 indexed soloGoalId,address indexed verifier,uint256 goalDeadline,uint256 reviewDeadline)',
  'event SoloGoalEvidenceSubmitted(uint256 indexed soloGoalId,address indexed owner,bytes32 digest,string uri)',
  'event SoloGoalApproved(uint256 indexed soloGoalId,address indexed owner,address indexed verifier,uint256 amount)',
  'event SoloGoalRejected(uint256 indexed soloGoalId,address indexed verifier,address indexed failureRecipient,uint256 amount,bytes32 reasonDigest)',
  'event SoloGoalCancelled(uint256 indexed soloGoalId)',
  'event SoloGoalExpired(uint256 indexed soloGoalId,address indexed failureRecipient,uint256 amount)',
  'event PayoutWithdrawn(address indexed recipient,uint256 amount)',
] as const;
